#!/usr/bin/env python3
"""
Example showing how GSS data enhances AI juror generation
"""

def show_gss_integration():
    print("=== HOW GSS DATA ENHANCES AI JUROR GENERATION ===\n")
    
    print("1. WHAT GSS ADDS TO YOUR SYSTEM")
    print("-" * 50)
    print("GSS provides REAL attitude data from 64,000+ Americans:")
    print("• Political views by demographics")
    print("• Social attitudes (death penalty, gun control, abortion)")
    print("• Trust in institutions (courts, government)")
    print("• Regional variations in beliefs")
    print("• Correlations between demographics and attitudes\n")
    
    print("2. GSS VARIABLES FOR JURY SIMULATION")
    print("-" * 50)
    print("Key variables that affect jury behavior:")
    print("\nPOLITICAL ORIENTATION:")
    print("• polviews: 1=extremely liberal to 7=extremely conservative")
    print("• partyid: 0=strong democrat to 6=strong republican")
    print("\nSOCIAL ATTITUDES:")
    print("• cappun: Death penalty support (affects criminal cases)")
    print("• gunlaw: Gun control views (affects 2nd amendment cases)")
    print("• trust: General trust in others (affects witness credibility)")
    print("\nINSTITUTIONAL TRUST:")
    print("• conjudge: Confidence in courts (affects judge instructions)")
    print("• confed: Trust in federal government (affects regulatory cases)")
    
    print("\n3. INTEGRATION WITH OTHER DATA")
    print("-" * 50)
    print("County → GSS Region → Attitudes → Personality → Juror")
    print("\nExample flow:")
    print("1. County: Los Angeles, CA")
    print("2. GSS Region: 9 (Pacific)")
    print("3. Regional attitudes from GSS:")
    print("   - More liberal (avg polviews: 3.8)")
    print("   - Higher education levels")
    print("   - More diverse social attitudes")
    print("4. Personality adjustments based on GSS:")
    print("   - Liberal views → +0.4 Openness")
    print("   - Urban educated → +0.2 Conscientiousness")
    print("5. Individual juror generated with these traits")
    
    print("\n4. EXAMPLE JUROR PROFILES WITH GSS")
    print("-" * 50)
    
    # Liberal Urban Juror
    print("\nLIBERAL URBAN JUROR (San Francisco):")
    print("Demographics: 35-year-old, college-educated, tech worker")
    print("GSS-based attitudes:")
    print("• Political view: 2 (liberal)")
    print("• Death penalty: Oppose (75% of similar demographics)")
    print("• Gun control: Support (82% of similar demographics)")
    print("• Marijuana: Should be legal (89% of similar demographics)")
    print("• Trust in courts: Moderate (conjudge=2)")
    print("Personality (adjusted for attitudes):")
    print("• High Openness (3.8) - willing to consider new arguments")
    print("• Low Conscientiousness (2.8) - flexible on rules")
    print("• High Agreeableness (3.5) - collaborative in deliberation")
    
    # Conservative Rural Juror  
    print("\nCONSERVATIVE RURAL JUROR (Rural Texas):")
    print("Demographics: 55-year-old, high school, farmer")
    print("GSS-based attitudes:")
    print("• Political view: 6 (conservative)")
    print("• Death penalty: Support (78% of similar demographics)")
    print("• Gun control: Oppose (71% of similar demographics)")
    print("• Marijuana: Should not be legal (65% of similar demographics)")
    print("• Trust in courts: High (conjudge=1)")
    print("Personality (adjusted for attitudes):")
    print("• Low Openness (2.7) - prefer traditional approaches")
    print("• High Conscientiousness (3.7) - strict on rules/law")
    print("• Moderate Agreeableness (3.1) - principled stance")
    
    print("\n5. HOW THIS AFFECTS DELIBERATIONS")
    print("-" * 50)
    print("GSS data helps predict:")
    print("• Initial positions on verdict")
    print("• Receptiveness to different arguments")
    print("• Trust in expert witnesses")
    print("• Interpretation of reasonable doubt")
    print("• Group dynamics and leadership")
    
    print("\nExample: Drug possession case")
    print("• Liberal juror (GSS grass=1): Sympathetic to defendant")
    print("• Conservative juror (GSS grass=2): Strict law enforcement")
    print("• Moderate juror: Swayable based on circumstances")
    
    print("\n6. DATA COMBINATIONS")
    print("-" * 50)
    print("COMPLETE JUROR = Census + GSS + Personality + Election")
    print("• Census: Age, race, education, income")
    print("• GSS: Social attitudes, political views, trust levels")
    print("• Personality: Big Five traits (adjusted by GSS)")
    print("• Election: County political context")
    print("\nResult: Realistic jurors with:")
    print("• Accurate demographics")
    print("• Research-based attitudes")
    print("• Psychologically valid personalities")
    print("• Locally appropriate political context")

if __name__ == "__main__":
    show_gss_integration()
    
    print("\n" + "="*60)
    print("IMPLEMENTATION NOTE:")
    print("To use GSS data:")
    print("1. Download from Kaggle (free account required)")
    print("2. Place in data/raw/gss_data.csv")
    print("3. API will automatically integrate with juror generation")
    print("="*60)