"""Analyze what matters in jury deliberation transcripts"""

print("JURY DELIBERATION TRANSCRIPT ANALYSIS")
print("=" * 50)

print("\n❌ WHAT DOESN'T MATTER (and should be removed):")
print("-" * 40)
print("• Physical gestures (*adjusts glasses*, *leans forward*)")
print("• Stage directions (*shifts in seat*, *taps chin*)")
print("• Body language descriptions")
print("• Filler phrases about posture")
print("\nThese add no legal value and just make responses longer.")

print("\n✓ WHAT ACTUALLY MATTERS:")
print("-" * 40)
print("• The legal arguments being made")
print("• References to specific evidence")
print("• Personal experiences that inform perspective")
print("• Direct responses to other jurors")
print("• Expressions of doubt or certainty")
print("• Questions about the evidence")
print("• Application of 'reasonable doubt' standard")

print("\n📊 GOOD THINGS IN YOUR TRANSCRIPT:")
print("-" * 40)
print("• Jurors reference their backgrounds (retail experience)")
print("• They discuss specific evidence gaps (no eyewitness)")
print("• They engage with the 'reasonable doubt' standard")
print("• Different perspectives emerge based on backgrounds")
print("• Some are skeptical of prosecution, others lean guilty")

print("\n🎯 KEY INSIGHTS:")
print("-" * 40)
print("1. The DeepSeek model is successfully roleplaying")
print("2. Each juror has a distinct perspective")
print("3. The deliberation is substantive despite the fluff")
print("4. Removing gestures would make it cleaner and faster")
print("5. The voting dynamics and faction formation are working")

print("\n💡 RECOMMENDATION:")
print("-" * 40)
print("Remove all physical actions/gestures to focus on pure")
print("legal argumentation. This will make the simulation:")
print("• Faster (shorter responses)")
print("• Cleaner (easier to read)")
print("• More professional (like real court transcripts)")
print("• More focused on what matters (the legal reasoning)")