"""Examples of varied, natural dialogue without repetitive phrases"""

print("❌ REPETITIVE 'GUT' PROBLEM:")
print("-" * 40)
print("Juror 1: 'My gut's telling me he's guilty...'")
print("Juror 2: 'My gut reaction is that he didn't do it...'") 
print("Juror 3: 'So my gut? When I see this footage...'")
print("↑ SOUNDS LIKE ROBOTS USING SAME SCRIPT")

print("\n✓ VARIED NATURAL SPEECH:")
print("-" * 40)
print("Juror 1: 'I think he's guilty. That footage is pretty clear.'")
print("Juror 2: 'I dunno... something doesn't add up here.'")
print("Juror 3: 'Well, when I see this stuff, it reminds me of...'")
print("↑ SOUNDS LIKE DIFFERENT REAL PEOPLE")

print("\n\nMORE VARIETY EXAMPLES:")
print("=" * 50)

print("\n1. DIFFERENT WAYS TO START:")
print("-" * 30)
print("• 'So here's the thing...'")
print("• 'I've been thinking about this...'")
print("• 'The way I see it...'")
print("• 'Honestly...'")
print("• 'You know what bugs me?'")
print("• 'Can I just say something?'")

print("\n2. SHOWING UNCERTAINTY:")
print("-" * 30)
print("• 'I'm not sure, but...'")
print("• 'Maybe I'm wrong, but...'")
print("• 'Hard to say...'")
print("• 'Could be either way...'")
print("• 'I'm torn on this...'")
print("• 'Part of me thinks...'")

print("\n3. PERSONAL REFERENCES:")
print("-" * 30)
print("• 'My dad worked security...'")
print("• 'At my job we see this...'")
print("• 'This happened to my neighbor...'")
print("• 'Back in college I...'")
print("• 'My wife always says...'")
print("• 'Where I grew up...'")

print("\n4. REACTIONS TO OTHERS:")
print("-" * 30)
print("• 'Wait, that's a good point...'")
print("• 'I disagree with that...'")
print("• 'Exactly! That's what I meant...'")
print("• 'Hold on, are you saying...?'")
print("• 'But what about...?'")
print("• 'Sarah, didn't you mention...?'")

print("\n5. WORKING CLASS vs EDUCATED SPEECH:")
print("-" * 30)
print("Working class:")
print("• 'Look, I work construction. This don't make sense.'")
print("• 'My buddy at the shop always says...'")
print("• 'I ain't buying it.'")

print("\nEducated professional:")
print("• 'In my experience as a nurse...'")
print("• 'This seems problematic to me.'")
print("• 'I have some concerns about...'")

print("\n6. REGIONAL/AGE DIFFERENCES:")
print("-" * 30)
print("Older person:")
print("• 'Back in my day...'")
print("• 'Now hold on just a minute...'")
print("• 'That's nonsense.'")

print("\nYounger person:")
print("• 'Okay but like...'")
print("• 'That's kinda weird...'")
print("• 'I'm not gonna lie...'")

print("\nSouthern:")
print("• 'Well I'll be...'")
print("• 'That dog won't hunt...'")
print("• 'Bless their heart...'")

print("\n\nKEY PRINCIPLE:")
print("=" * 50)
print("Each juror should sound like a DIFFERENT person with their own:")
print("• Vocabulary level")
print("• Regional phrases") 
print("• Age-appropriate language")
print("• Education level")
print("• Personal experiences")
print("• Emotional style")
print("\nNOT everyone using the same 'gut reaction' template!")